///////////////////////////////////////////////////////////
//  ConversionHandler.cs
//  Implementation of the Class ConversionHandler
//  Generated by Enterprise Architect
//  Created on:      19-Mar-2019 7:18:07 PM
///////////////////////////////////////////////////////////




public abstract class ConversionHandler {

	protected ConversionHandler successor;

	public abstract double HandleConversion(string unitRequested, double figure);

	public void SetSuccessor(ConversionHandler unit)
    {
        this.successor = unit;
	}

}