///////////////////////////////////////////////////////////
//  FootHandler.cs
//  Implementation of the Class FootHandler
//  Generated by Enterprise Architect
//  Created on:      19-Mar-2019 7:18:27 PM
///////////////////////////////////////////////////////////




public class FootHandler : ConversionHandler
{

	public override double HandleConversion(string unitRequested, double figure)
    {
        if (unitRequested == "Foot")
        {
            return figure * 3280.84;
        }
        else
        {
            return successor.HandleConversion(unitRequested, figure);
        }
    }

}