///////////////////////////////////////////////////////////
//  MileHandler.cs
//  Implementation of the Class MileHandler
//  Generated by Enterprise Architect
//  Created on:      19-Mar-2019 7:18:24 PM
///////////////////////////////////////////////////////////




public class MileHandler : ConversionHandler
{

	public override double HandleConversion(string unitRequested, double figure)
    {
        if (unitRequested == "Mile")
        {
            return figure * 0.621371;
        }
        else
        {
            return successor.HandleConversion(unitRequested, figure);
        }
	}

}