///////////////////////////////////////////////////////////
//  YardHandler.cs
//  Implementation of the Class YardHandler
//  Generated by Enterprise Architect
//  Created on:      19-Mar-2019 7:18:26 PM
///////////////////////////////////////////////////////////




public class YardHandler : ConversionHandler
{

	public override double HandleConversion(string unitRequested, double figure)
    {
        if (unitRequested == "Yard")
        {
            return figure * 1093.61;
        }
        else
        {
            return successor.HandleConversion(unitRequested, figure);
        }
    }

}